#include <string>

std::string taunts[] = {
    "Yes.",
    "No.",
    "Maybe.",
    "I need Wealth. I need wealth, alright? Wealth.",
    "I need Timonium.",
    "I need energy.",
    "I need resources.",
    "Do you need resources?",
    "I'm under attack!",
    "Hey, this noob's rushin' me.",
    "Build...more...troops...",
    "Work on your economy, hmm?",
    "Wait for my signal to attack.",
    "Attack!",
    "Move troops here.",
    "Grab some territory.",
    "Gonna boom!",
    "Gonna rush.",
    "You should boom.",
    "You should rush.",
    "You should turtle.",
    "Huh, wanna ally?",
    "Wanna make peace?",
    "Of course you realize, this means war.",
    "Where should we attack?",
    "When should we attack?",
    "Where is the enemy?",
    "Where is the Timonium?",
    "Red.",
    "Blue.",
    "Green.",
    "Yellow.",
    "Light blue.",
    "Orange.",
    "Purple.",
    "Pink.",
    "I need help here.",
    "Uh, hey dude, a little help here.",
    "Attack here.",
    "Defend here.",
    "Build ground units!",
    "Build air units!",
    "Let me know how that works out for ya.",
    "Ha Ha!",
    "You okay over there?",
    "And stay out!",
    "Go on, I dare ya, storm it!",
    "They're attacking my capital!",
    "Let the game begin!",
    "We're doomed!",
    "Wanna give up?",
    "Victory is mine!",
    "On my way.",
    "I'm tryin' to send some help.",
    "Gotcha covered.",
    "It shall be done.",
    "Let me get right on that.",
    "Heh heh heh, sweet.",
    "That's what I'm talkin' about.",
    "Consider it taken care of.",
    "Sounds like a plan.",
    "Aaaaaaagh! The humanity!",
    "They keep on rising!!!!!!",
    "Su-who? Sawu!",
    "Hey! Dominate THIS!",
    "Dominance! Dominance! Dominance!",
    "You summoned THAT?",
    "Star Bolt! Run for your lives!!!",
    "Ya, you and what army!?",
    "Oh, that army.",
    "You call that an army? Ha!",
    "Oh lookie, where did your army go?",
    "That's one big dead army!",
    "Aaaaaeeeeee! Splat!",
    "Now you see it... Now you don't.",
    "That was a truly painful experience.",
    "DOGE? Oh, I'VE been pronouncing it Doggy!",
    "Say what you will, but those Cuotl are really shiny, and I like shiny.",
    "Okay, how 'bout I ask nicely, and YOU... STOP...KILLING... ME!?",
    "Yeah, but aside from that army, and that OTHER army, what you got? NOTHIN!",
    "Ain't no party like a Clockwork Party, cuz a Clockwork Party don't stop!",
    "Hero fall down go boom.",
    "This is payback for that time you did that thing with the stuff. Yeah.",
    "Well oh yeah.",
    "Okay, but the next time we play, I am NOT falling for that.",
    "I've got this terrible premonition... Something about you and death.",
    "I hope you like explosions and screaming...",
    "Does you insurance policy cover Giant Robots?",
    "I have such a surprise for you.",
    "I wasn't sure what to get you, bet I settled on a slow and painful death.",
    "You're gonna wish you bought that asbestos underwear.",
    "So if I push this button... Ohhhh. Yeah, that's gonna be fun for you.",
    "Hey? Wait! No, wait! I wasn't ready!",
    "No no, you want the other city next door. It's way more vulnerable.",
    "I'm gonna go curl up in a ball and die now, thanks.",
    "I just vacuumed in here! Now look at this mess you made!",
    "Hey, did I ask you to come here and wreck all my stuff? I think not.",
    "I did NOT need that.",
    "You know what YOUR problem is? Me.",
    "I know, I know, you're going to crush me, blah blah blah.",
};
